name: paprika-kcl
channels:
  - conda-forge
  - ambermd
  - omnia
dependencies:
  # Base depends
  - python=3.6
  - pip
  - numpy
  - scipy
  - parmed
  - pymbar
  - ambertools=18
  - pip:
    - git+https://github.com/slochower/paprika/@720187d9f38affd3e091f3dfa21ac9b318dbbdd8

# We can either install paprika from conda-forge
# or specify a commit on GitHub
